[project]
name = "JukeBot"
version = "0.1.0"
description = "A music bot for Discord using Disnake"
requires-python = ">=3.12,<4"
authors = [{ name = "Dysta", email = "xav4098@gmail.com" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "asyncstdlib>=3.13.1,<4",
  "disnake[speed, voice]>=2.12.0,<3",
  "loguru>=0.7.3,<0.8",
  "pyaml>=26.2.1,<27",
  "python-dotenv>=1.2.1,<2",
  "shazamio>=0.8.1,<0.9",
  "taskipy>=1.14.1,<2",
  "yt-dlp>=2026.2.21,<2027",
]

[project.optional-dependencies]
speed = [
  "uvloop>=0.22.1",
]

[dependency-groups]
dev = [
  "ruff>=0.16.1",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
extend-exclude = ["tests", ".tools"]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]

[tool.taskipy.tasks]
clean = { cmd = "ruff check . --fix --unsafe-fixes", help = "remove unused code/imports and sort imports" }
format = { cmd = "ruff format .", help = "format code" }
start = { cmd = "python -m jukebot", help = "run the bot" }
tests = { cmd = "python -m unittest -v", help = "run all the tests" }

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-root = ""
