# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: JukeBot CI Full

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  unit-tests:
    name: Unittest Python
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      # - name: Cache dependencies
      #   uses: actions/cache@v6
      #   with:
      #     path: ~/.cache/uv/virtualenvs
      #     key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
      #     restore-keys: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}

      - name: Install dependencies
        run: uv sync --frozen --no-dev

      - name: Launch unit test
        run: uv run task tests
        env:
          CI: true
